Update dev_pcp_pipline_like_crmdev.yaml

diff --git a/.github/workflows/dev_pcp_pipline_like_crmdev.yaml b/.github/workflows/dev_pcp_pipline_like_crmdev.yaml
--- a/.github/workflows/dev_pcp_pipline_like_crmdev.yaml
+++ b/.github/workflows/dev_pcp_pipline_like_crmdev.yaml
@@ -89,15 +89,22 @@ jobs:
       - name: Change APP_ENV in .env.local
         if: ${{ github.event.inputs.change_app_env == true && github.event.inputs.app_env_choice != '' }}
         run: |
-          echo "Switching APP_ENV to: ${{ github.event.inputs.app_env_choice }}"
-          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -T -J $SERVER_USER@${{ secrets.PUBLIC_SERVER_IP_DEV }} $SERVER_USER@${{ secrets.PRIVATE_SERVER_IP_DEV }} <<EOF
-          # Update APP_ENV in .env.local
-          sed -i 's/\\(APP_ENV=\\).*/\\1${{ github.event.inputs.app_env_choice }}' $APP_ROOT/.env.local
-          EOF
-          
-          # Display modified content of .env.local
-          modified_content=$(ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -T -J $SERVER_USER@${{ secrets.PUBLIC_SERVER_IP_DEV }} $SERVER_USER@${{ secrets.PRIVATE_SERVER_IP_DEV }} "cat $APP_ROOT/.env.local")
-          echo "Modified .env.local content: $modified_content"
+             echo "Switching APP_ENV to: ${{ github.event.inputs.app_env_choice }}"
+             ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -T -J $SERVER_USER@${{ secrets.PUBLIC_SERVER_IP_DEV }} $SERVER_USER@${{ secrets.PRIVATE_SERVER_IP_DEV }} <<EOF
+              # Check if .env.local exists
+              if [ ! -f "$APP_ROOT/.env.local" ]; then
+              echo ".env.local not found!"
+               exit 1
+               fi
+
+                 # Update APP_ENV in .env.local
+                  sed -i "s/\(APP_ENV=\).*/\1${{ github.event.inputs.app_env_choice }}/" $APP_ROOT/.env.local
+                   EOF
+    
+                # Display modified content of .env.local
+               modified_content=$(ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -T -J $SERVER_USER@${{ secrets.PUBLIC_SERVER_IP_DEV }} $SERVER_USER@${{ secrets.PRIVATE_SERVER_IP_DEV }} "cat $APP_ROOT/.env.local")
+                echo "Modified .env.local content: $modified_content"
+
 
 
       # Step 5: Execute Extra Commands
